/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RR.UI;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Simulator extends javax.swing.JFrame {

    /**
     * Creates new form Simulator
     */
    private DefaultTableModel rqmodel;
    private DefaultTableModel fmodel;
    private JLabel[] labelList = new JLabel[54];
    
    private int time;

    public Simulator() {

        initComponents();

        rqmodel = (DefaultTableModel) readyQTable.getModel();
        fmodel = (DefaultTableModel) finishedTable.getModel();
        labelList[0] = lb0;
        labelList[1] = lb1;
        labelList[2] = lb2;
        labelList[3] = lb3;
        labelList[4] = lb4;
        labelList[5] = lb5;
        labelList[6] = lb6;
        labelList[7] = lb7;
        labelList[8] = lb8;
        labelList[9] = lb9;
        labelList[10] = lb10;
        labelList[11] = lb11;
        labelList[12] = lb66;
        labelList[13] = lb67;
        labelList[14] = lb68;
        labelList[15] = lb69;
        labelList[16] = lb70;
        labelList[17] = lb71;
        labelList[18] = lb72;
        labelList[19] = lb73;
        labelList[20] = lb74;
        labelList[21] = lb75;
        labelList[22] = lb76;
        labelList[23] = lb77;
        labelList[24] = lb12;
        labelList[25] = lb13;
        labelList[26] = lb14;
        labelList[27] = lb15;
        labelList[28] = lb16;
        labelList[29] = lb17;
        labelList[30] = lb18;
        labelList[31] = lb19;
        labelList[32] = lb20;
        labelList[33] = lb21;
        labelList[34] = lb22;
        labelList[35] = lb23;
        labelList[36] = lb24;
        labelList[37] = lb25;
        labelList[38] = lb26;
        labelList[39] = lb27;
        labelList[40] = lb28;
        labelList[41] = lb29;
        labelList[42] = lb30;
        labelList[43] = lb31;
        labelList[44] = lb32;
        labelList[45] = lb33;
        labelList[46] = lb34;
        labelList[47] = lb35;
        labelList[48] = lb30;
        labelList[49] = lb31;
        labelList[50] = lb32;
        labelList[51] = lb33;
        labelList[52] = lb34;
        labelList[53] = lb35;

       
        for (JLabel lb : labelList) {
            lb.setVisible(false);
        }
        
    }

    public void addtoReadyQueue(String pid, int remainingTime) {

        rqmodel.addRow(new Object[]{pid, remainingTime});
    }

    public void removeFromReadyQueue() {

        rqmodel.removeRow(0);
    }

    public void addFinishedProcess(String pid, int finishedTime, double TTime) {
        Vector newRow = new Vector();
        newRow.add(pid);
        newRow.add(finishedTime);
        newRow.add(TTime);
        fmodel.addRow(newRow);
    }

    public void setGanttChart(String pid) {
        
        labelList[time].setText(pid);        
        labelList[time].setVisible(true);        

    }

    public void setTime(int time) {
        this.time = time;
        tLabel.setText(Integer.toString(time));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        readyQTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        finishedTable = new javax.swing.JTable();
        jLabel2 = new JLabel();
        jLabel5 = new JLabel();
        tLabel = new JLabel();
        lb1 = new JLabel();
        lb0 = new JLabel();
        lb2 = new JLabel();
        lb3 = new JLabel();
        lb4 = new JLabel();
        lb5 = new JLabel();
        lb6 = new JLabel();
        lb7 = new JLabel();
        lb8 = new JLabel();
        lb9 = new JLabel();
        lb10 = new JLabel();
        lb11 = new JLabel();
        lb66 = new JLabel();
        lb67 = new JLabel();
        lb68 = new JLabel();
        lb69 = new JLabel();
        lb70 = new JLabel();
        lb71 = new JLabel();
        lb72 = new JLabel();
        lb73 = new JLabel();
        lb74 = new JLabel();
        lb75 = new JLabel();
        lb76 = new JLabel();
        lb77 = new JLabel();
        lb12 = new JLabel();
        lb13 = new JLabel();
        lb14 = new JLabel();
        lb15 = new JLabel();
        lb16 = new JLabel();
        lb17 = new JLabel();
        lb18 = new JLabel();
        lb19 = new JLabel();
        lb20 = new JLabel();
        lb21 = new JLabel();
        lb22 = new JLabel();
        lb23 = new JLabel();
        lb24 = new JLabel();
        lb25 = new JLabel();
        lb26 = new JLabel();
        lb27 = new JLabel();
        lb28 = new JLabel();
        lb29 = new JLabel();
        lb30 = new JLabel();
        lb31 = new JLabel();
        lb32 = new JLabel();
        lb33 = new JLabel();
        lb34 = new JLabel();
        lb35 = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ready queue");

        readyQTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Remaining time"
            }
        ) {
            Class[] types = new Class [] {
                String.class, Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(readyQTable);
        if (readyQTable.getColumnModel().getColumnCount() > 0) {
            readyQTable.getColumnModel().getColumn(0).setResizable(false);
            readyQTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jScrollPane1.setViewportView(jScrollPane3);

        finishedTable.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Finished time", "Turnaround time"
            }
        ) {
            Class[] types = new Class [] {
                String.class, Integer.class, Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(finishedTable);
        if (finishedTable.getColumnModel().getColumnCount() > 0) {
            finishedTable.getColumnModel().getColumn(0).setResizable(false);
            finishedTable.getColumnModel().getColumn(1).setResizable(false);
            finishedTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("finished processes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Time");

        tLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        lb1.setBackground(new Color(51, 204, 255));
        lb1.setText("1");
        lb1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb0.setBackground(new Color(51, 204, 255));
        lb0.setText("1");
        lb0.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb2.setBackground(new Color(51, 204, 255));
        lb2.setText("1");
        lb2.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb3.setBackground(new Color(51, 204, 255));
        lb3.setText("1");
        lb3.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb4.setBackground(new Color(51, 204, 255));
        lb4.setText("1");
        lb4.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb5.setBackground(new Color(51, 204, 255));
        lb5.setText("1");
        lb5.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb6.setBackground(new Color(51, 204, 255));
        lb6.setText("1");
        lb6.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb7.setBackground(new Color(51, 204, 255));
        lb7.setText("1");
        lb7.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb8.setBackground(new Color(51, 204, 255));
        lb8.setText("1");
        lb8.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb9.setBackground(new Color(51, 204, 255));
        lb9.setText("1");
        lb9.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb10.setBackground(new Color(51, 204, 255));
        lb10.setText("1");
        lb10.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb11.setBackground(new Color(51, 204, 255));
        lb11.setText("1");
        lb11.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb66.setBackground(new Color(51, 204, 255));
        lb66.setText("1");
        lb66.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb67.setBackground(new Color(51, 204, 255));
        lb67.setText("1");
        lb67.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb68.setBackground(new Color(51, 204, 255));
        lb68.setText("1");
        lb68.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb69.setBackground(new Color(51, 204, 255));
        lb69.setText("1");
        lb69.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb70.setBackground(new Color(51, 204, 255));
        lb70.setText("1");
        lb70.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb71.setBackground(new Color(51, 204, 255));
        lb71.setText("1");
        lb71.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb72.setBackground(new Color(51, 204, 255));
        lb72.setText("1");
        lb72.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb73.setBackground(new Color(51, 204, 255));
        lb73.setText("1");
        lb73.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb74.setBackground(new Color(51, 204, 255));
        lb74.setText("1");
        lb74.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb75.setBackground(new Color(51, 204, 255));
        lb75.setText("1");
        lb75.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb76.setBackground(new Color(51, 204, 255));
        lb76.setText("1");
        lb76.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb77.setBackground(new Color(51, 204, 255));
        lb77.setText("1");
        lb77.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb12.setBackground(new Color(51, 204, 255));
        lb12.setText("1");
        lb12.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb13.setBackground(new Color(51, 204, 255));
        lb13.setText("1");
        lb13.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb14.setBackground(new Color(51, 204, 255));
        lb14.setText("1");
        lb14.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb15.setBackground(new Color(51, 204, 255));
        lb15.setText("1");
        lb15.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb16.setBackground(new Color(51, 204, 255));
        lb16.setText("1");
        lb16.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb17.setBackground(new Color(51, 204, 255));
        lb17.setText("1");
        lb17.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb18.setBackground(new Color(51, 204, 255));
        lb18.setText("1");
        lb18.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb19.setBackground(new Color(51, 204, 255));
        lb19.setText("1");
        lb19.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb20.setBackground(new Color(51, 204, 255));
        lb20.setText("1");
        lb20.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb21.setBackground(new Color(51, 204, 255));
        lb21.setText("1");
        lb21.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb22.setBackground(new Color(51, 204, 255));
        lb22.setText("1");
        lb22.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb23.setBackground(new Color(51, 204, 255));
        lb23.setText("1");
        lb23.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb24.setBackground(new Color(51, 204, 255));
        lb24.setText("1");
        lb24.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb25.setBackground(new Color(51, 204, 255));
        lb25.setText("1");
        lb25.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb26.setBackground(new Color(51, 204, 255));
        lb26.setText("1");
        lb26.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb27.setBackground(new Color(51, 204, 255));
        lb27.setText("1");
        lb27.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb28.setBackground(new Color(51, 204, 255));
        lb28.setText("1");
        lb28.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb29.setBackground(new Color(51, 204, 255));
        lb29.setText("1");
        lb29.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb30.setBackground(new Color(51, 204, 255));
        lb30.setText("1");
        lb30.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb31.setBackground(new Color(51, 204, 255));
        lb31.setText("1");
        lb31.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb32.setBackground(new Color(51, 204, 255));
        lb32.setText("1");
        lb32.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb33.setBackground(new Color(51, 204, 255));
        lb33.setText("1");
        lb33.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb34.setBackground(new Color(51, 204, 255));
        lb34.setText("1");
        lb34.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        lb35.setBackground(new Color(51, 204, 255));
        lb35.setText("1");
        lb35.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(281, 281, 281))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(tLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb66, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb67, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb68, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb69, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb70, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb71, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb72, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb73, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb74, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb75, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb76, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb77, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(tLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb66, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb68, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb67, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb69, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb70, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb71, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb72, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb74, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb73, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb75, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb76, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb77, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb13, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb18, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb20, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb19, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb21, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb22, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb23, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb24, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb26, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb25, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb27, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb29, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb32, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb31, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb33, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb34, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb35, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable finishedTable;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private JLabel lb0;
    private JLabel lb1;
    private JLabel lb10;
    private JLabel lb11;
    private JLabel lb12;
    private JLabel lb13;
    private JLabel lb14;
    private JLabel lb15;
    private JLabel lb16;
    private JLabel lb17;
    private JLabel lb18;
    private JLabel lb19;
    private JLabel lb2;
    private JLabel lb20;
    private JLabel lb21;
    private JLabel lb22;
    private JLabel lb23;
    private JLabel lb24;
    private JLabel lb25;
    private JLabel lb26;
    private JLabel lb27;
    private JLabel lb28;
    private JLabel lb29;
    private JLabel lb3;
    private JLabel lb30;
    private JLabel lb31;
    private JLabel lb32;
    private JLabel lb33;
    private JLabel lb34;
    private JLabel lb35;
    private JLabel lb4;
    private JLabel lb5;
    private JLabel lb6;
    private JLabel lb66;
    private JLabel lb67;
    private JLabel lb68;
    private JLabel lb69;
    private JLabel lb7;
    private JLabel lb70;
    private JLabel lb71;
    private JLabel lb72;
    private JLabel lb73;
    private JLabel lb74;
    private JLabel lb75;
    private JLabel lb76;
    private JLabel lb77;
    private JLabel lb8;
    private JLabel lb9;
    private javax.swing.JTable readyQTable;
    private JLabel tLabel;
    // End of variables declaration//GEN-END:variables
}
